var GAME_LEVELS = [
  ["                                                                                   ",
   "                                                                               ",
   "                                                                                   ",
   "                o o                                                                ",
   "                                      xxxx                                         ",
   "         xxxxx       xxxxx                       o                                 ",
   "                             f                              o                      ",
   "                          xxxxxx              xxxxxx                               ",
   "  xxxxx        x!!!x                                    xxE     x                  ",
   "               x!!!x                                     xxxxxxxx                  ",
   "               xxxxx                                                               ",
   "          xxxx                             xxxxx   xxxxx         o       o         ",
   "                                           x   x!!!x                               ",
   "                         o          fff    x   x!!!x         xE            x       ",
   "                                   xxxxxxxxx   xxxxx         xxxxxxxxxxxxxxx       ",
   "     xxxx                                                 xxxx                     ",
   " @   xxxx                        f                               o                 ",   
   "xxxxxxxxxxx                     xxxx                                            xxx",
   "xxxxxxxxxxx    o      f     xxxxxxxx         xxx       x    xx       xxxxxxxx!!!xxx",
   "xxxxxxxxxxx         xxxxx   xxxxxxxx   x            o  x!!!!xxE      xxxxxxxx!!!xxx",
   "xxxxxxxxxxxE        xxxxx!!!xxxxxxxx!!!x               x!!!!xxxxxxxxxxxxxxxxx!!!xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxE       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                        x                                                                                         ",
   "                        x                                                                                         ",
   "                        x                                                                                        ", 
   "                      @ x                                         o                                              ",
   "               xxxxxxxxxx                                                                                        ",
   "                                          xxxxxxx                                                                ",
   "                            o                   x    E         x                                                 ",
   "                                                xxxxxxxxxxxxxxxx!!!xxxxx                               o         ", 
   " xxxx                                                          x!!!x                                             ",
   "                  xxxxxx         xxxxxxx        o              xxxxx          o                                  ",
   "                  x    x         x     x                                  f                           xxxx       ",
   "                  x    x   E   xxx     xxxxxxx                           xxxxxxxx!!!!!!x                         ",
   "              xxxxx o  xxxxxxxxx             x   E  x                           x!!!!!!x                         ",
   "xxxxxx                                       xxxxxxxx                           x!!!!!!x                         ",
   "     x                                                                          xxxxxxxx                         ",
   "     x                                                                                                           ",
   "     x!!!!!x      xxxxxx                                     xxxxxxxx                      x  E  xxxx            ",
   "     x!!!!!x           xf                                                                  xxxxxxx               ",
   "     x!!!!!x           xxxxxx                  o                                                        xxxxxxxx ",
   "     x!!!!!x                 xxxxxx!!!x                                                                          ",
   "     xxxxxxx                      x!!!x                                   xxxxx        o                         ",
   "                                  x!!!xxxxxxx                             xxxxx                                  ",
   "       o                          xxxxx     xxxxx       xxxx              xxxxx                    xxxxxx        ",
   "               xx                                                   xxxxxxxxxxxx      f            xxxxxx        ",
   "                                                                    xxxxxxxxxxxx    xxxxxx       xxxxxxxxxxxxxxxx",
   "     xxxx                                                o   xxxx   xxxxxxxxxxxx    xxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                                                             x  x!!!xxxxxxxxxxxxffffxxxxxx!!!!xxxxxxxxxxxxxxxxxxx",
   "                                                             x  x!!!xxxxxxxxxxxx!!!!xxxxxx!!!!xxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!xxxxxxxxxxxxxfffffxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
                                                                                                                      
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                      @                                                                                  ",
   "                      x                                                                                  ",
   "                     xxx                                                                                 ",
   "                      x                                                                                  ",
   "                    xxxxx                                          o                                     ",
   "                      x                                    xxxxx                       o                 ",
   "                   xxxxxxx                                 x   x                                         ",
   "             o        x                                xxxxx   x                                         ",
   "                      x                                x       xxxxxxx             xxxx                  ",
   "      xxxxx       xxxxxxxxx                       xxxxxxff                         x!!x                  ",
   "      x   x       x                            xxxxxxxxxxxxx                       x!!x                  ",
   "      x   x   E   x                            x           x                      xxxxxx                 ",
   "      x   xxxxxxxxx          xxxxxx            x       o   x                       x  xfff               ",
   "      x                                        x         ffx                    xxxxxxxxxxxxx            ",
   "      xffffffff         o                      x      xxxxxx         o          x           x            ",
   "      xxxxxxxxx                          xxxx                                xxxxfffffx     x            ",
   "              x                                                              x  xxxxxxx  o  xxxxxx       ",
   "              x        xxxxxx        xx                               xxxxxxxx                        xx ",
   "              x             x        xx                                                                  ",
   "xxxxx         x             x   E    xx                          xx                xxx          xxxxxx   ",
   "    x                       xxxxxxxxxxx               xxxxx!!!!!!x                        xx             ",
   "    x                                 xff             x   x!!!!!!x                      o  x             ",
   "    xxxxxxxxxxxxx                     xxxxxxxxxx!!!xxxx   x!!!!!!x      xxx                x             ",
   "                                               x!!!x      xxxxxxxx             x      E    x             ",
   "  o                                            xxxxx                           xxxxxxxxxxxxx             ",
   "                      xxxxxxx                                                  x                         ",
   "   	xxxxxxxxx                                            o              xxxxxxxx     o          xxxxxxxxx",
   "   	x!!!!!!!x                                                   xx             x                x        ",
   "xxxxx!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx            xx             xxxxxxxxxxxxxxxxxx        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!x   xxxx     xxxxxx                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!x E x!!x     x!!!!x                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!xxxxx!!x  E  x!!!!xxxxx   xxxxxx       xxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                               o                                ",
   "                                                     f                                                     fffff",
   "                          o                       xxxx                                                    xxxxxx",
   "               xxxx     xxxx                 xxxxxx                                            ff              x",
   "                                                                                          xxxxxxxxxxxx          ",
   "                                                                        xxxxxxxxxxxxxxx!!!x                     ",
   "                                f                o                      x             x!!!x                     ",
   "                             xxxxxxx                            xxxxxxxxx             xxxxx                     ",
   "                                   x                                        o                                   ",
   "      xxxxxxx       xxxxxx         x                                                                            ",
   " @    x     x                      xxxxx  E  xxxxxxx  E  xxxxxx                                                 ",
   "xxxxxxx     x    o                     xxxxxxx     xxxxxxx                  xx                                  ",
   "            x                                                                                                   ",
   "            x                                                                                                   ",
   "                                                      xxxxxxxxxx                         xxxx                   ",
   "  xxx                                                          x                       xxx                      ",
   "      xxxxxxxxx                           x    E   x           xff                    xx        ffff            ",
   "   fffx                    o              xxxxxxxxxx           xxxxxxxxxx   E    xxxxxxx      xxxxxxxxxx        ",
   "   xxxx                                                                 xxxxxxxxxx                              ",
   "             xff                xxxx                                                      o                     ",
   "             xxxxxxxx                                  xxx                                                      ",
   "                                                                                                                ",
   "!                          x   E  x                                                                             ",
   "!              xxxxxxxxx o xxxxxxxx                         xxxxxxx                                         xx  ",
   "!                      x   x                                x     x                 x                       xxff",
   "!                                                           x  o  x                 x                 xxxxxxxxxx",
   "!!                                               xx     xxxxx     xxx             xxx          xxxx   xxxxxxxxxx",
   "!!!!!!!!x                xxxxx               xxxxxx     x                                      xxxx!!!xxxxxxxxxx",
   "xx!!!!!!x                x o        x!!!!!xxxx!!!!!                                            xxxxxxxxxxxxxxxxx",
   "xx!!!!!!x      E         x         fx!!!!!x!!!!!!!!ffff             ff              xE         xxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
